# Architecture
arch: WideResNet50_2

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: ImageNet

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.256
lr_policy: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.000030517578125
momentum: 0.875
batch_size: 256
label_smoothing: 0.1

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1 # Override
init: signed_constant 
mode: fan_in
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 20