# Architecture
arch: cResNet18

# ===== Dataset ===== #
data: /mnt
set: CIFAR10
name: sample_cifar

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 400
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0 #0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SampleSubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
prune_rate: -1
init: kaiming_normal
# scale_fan: True

# ===== Hardware setup ===== #
workers: 4