# Architecture
arch: cResNet18 

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
prune_rate: 0.0

# ===== Hardware setup ===== #
workers: 4